version: "3.4"
services:
  livrariaiba_vue:
    container_name: livrariaiba
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 3000
    volumes:
      - ./:/var/www/html/app
    tty: true
    # command: "npm install && npm run dev"